### PR TITLE
Probably my last contibutions

### PR DESCRIPTION
**Pull request by SIsilicon**
I wish I can do more, but I have other projects I want to do myself. So here are my final additions/changes.
- the toon water looks more like the one at Godot devs.
- add planar reflections on a couple of the presets. The oceans one is kinda broken.
- the buoyancy data has three modes: single, auto, and manual. Right now to change between one and the other, you must edit that parameter in the inspector, exit it and go back. The values should be self I explanatory. If not just ask.
- the buoyancy data points can also be edited manually from the editor viewport. Pressing x y or z will lock the movement along its local axis. And holding shift and one of those keys will lock it to that axis plane.
- the boat has a sort of 'depth mask' I mentioned earlier in the discussion issue. 
- started to make some of the water presets extend from a base water script `water.gd` which manages the planar reflections, among other things.

Any questions or issues, just say it.

### CODE REVIEW

**Comment by ywaby** [comment]
Thank for your job. your are energetic.
I will continue the project

**Comment by SIsilicon** [comment]
I'm not going to merge this. You will. Hope to see this on Godot asset store. The ocean I made in this is better than the one I put on the asset store.

**Comment by ywaby** [comment]
I will merge it alfter my 2d finish.

**Comment by ywaby** [comment]
miss rain.gd and toon water texture

**Comment by SIsilicon** [comment]
Ok I added them.

**Comment by SIsilicon** [comment]
Hello?

**Comment by ywaby** [comment]
I still work on it

**Comment by SIsilicon** [comment]
Hmm...
Something must be keeping you busy.
Real life stuff?

**Comment by SIsilicon** [comment]
Should I go ahead and merge it?

**Comment by SIsilicon** [comment]
. . .
Something keeping you up? School maybe?

**Comment by ywaby** [comment]
sorry,i just lost passion,and move my attention to others. If you want, you can go ahead.

**Comment by SIsilicon** [comment]
Ok

**Pull request merged**
